spring:
  datasource:
    username: ${AUTH_USERNAME:demo}
    password: ${AUTH_PASSWORD:secret}
    url: ${AUTH_DB:jdbc:postgresql://localhost:5432/kiss-demo?currentSchema=auth}
  profiles:
    active: logging

server:
  port: 6012
