language: java
dist: xenial
os: linux
jdk: openjdk13

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - docker

install:
  - ./gradlew classes

script:
  - ./gradlew build
  - docker build -t michaelilyin/kiss-spring-demo-goods:latest ./demo/goods

deploy:
  - provider: script
    script: bash deploy.sh
    on:
      branch: master

  - provider: script
    script: echo deploy to cloud
    on:
      branch: master
