language: java
dist: xenial
os: linux
jdk: openjdk13

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - docker

install: skip

script:
  - ./gradlew build
  - docker build -t michaelilyin/kiss-spring-demo-goods:latest ./demo/goods

before_deploy:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

deploy:
  - provider: script
    script: bash publish.sh
    on:
      branch: master

  - provider: script
    script: bash deploy.sh
    on:
      branch: master

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
