apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kiss-cloud
  labels:
    app: goods
  name: goods
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: goods
  strategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: kiss-cloud
      labels:
        app: goods
    spec:
      containers:
      - image: michaelilyin/kiss-spring-demo-goods:latest
        imagePullPolicy: Always
        name: kiss-cloud-goods
---
apiVersion: v1
kind: Service
metadata:
  namespace: kiss-cloud
  labels:
    app: goods
  name: goods
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: goods
  type: ClusterIP


---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kiss-cloud
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: kiss-cloud
      labels:
        app: auth
    spec:
      containers:
        - image: jboss/keycloak:latest
          imagePullPolicy: Always
          name: kiss-cloud-auth
          env:
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  key: kiss-cloud-keycloak
                  name: keycloak.user
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: kiss-cloud-keycloak
                  name: keycloak.password
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              valueFrom:
                secretKeyRef:
                  key: kiss-cloud-keycloak
                  name: db.addr
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: kiss-cloud-keycloak
                  name: db.port
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: kiss-cloud-keycloak
                  name: db.database
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  key: kiss-cloud-keycloak
                  name: db.schema
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: kiss-cloud-keycloak
                  name: db.user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: kiss-cloud-keycloak
                  name: db.password
---
apiVersion: v1
kind: Service
metadata:
  namespace: kiss-cloud
  labels:
    app: auth
  name: auth
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: auth
  type: ClusterIP


---


apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: kiss-cloud
  name: kiss-cloud-auth-ingress
spec:
  rules:
    - host: auth.michaelilyin.ru
      http:
        paths:
          - path: .*
            backend:
              serviceName: auth
              servicePort: 8080


---


apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: kiss-cloud
  name: kiss-cloud-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2$3
spec:
  rules:
    - host: cl.michaelilyin.ru
      http:
        paths:
          - path: /(api|auth)/intra(/|$)(.*)
            backend:
              serviceName: goods
              servicePort: 8080
