graphql:
  packages:
    - net.kiss.demo.cart
  federation:
    enabled: true

spring:
  data:
    mongodb:
      password: secret
      username: demo
      database: kiss-demo

server:
  port: 6011

logging:
  level:
    ROOT: INFO
#    graphql: TRACE
#    com.expediagroup: TRACE
#    org.springframework.http.codec: DEBUG
