version: "3"
services:
  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_DB: demo-shopping-list
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - ./bin/db/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
