version: "3"
services:
  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_DB: kiss-demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - kiss_demo_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    build:
      context: database
    environment:
      LIQUIBASE_URL: jdbc:postgresql://postgres:5432/backend
      LIQUIBASE_USERNAME: backend
      LIQUIBASE_PASSWORD: secret
      LIQUIBASE_CHANGELOG: /liquibase/changelog.yaml
    restart: on-failure
    depends_on:
      - postgres

volumes:
  kiss_demo_pg_data:
    external: true
