version: "3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: kiss-demo
    ports:
      - 27017-27019:27017-27019
    volumes:
#      - kiss_demo_mongo_data:/data/db
      - ./bin/db/mongo:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_DB: kiss-demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
#      - kiss_demo_pg_data:/var/lib/postgresql/data
      - ./bin/db/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    build:
      context: postgres
    environment:
      LIQUIBASE_URL: jdbc:postgresql://postgres:5432/kiss-demo
      LIQUIBASE_USERNAME: demo
      LIQUIBASE_PASSWORD: secret
      LIQUIBASE_CHANGELOG: /liquibase/changelog.yaml
    restart: on-failure
    depends_on:
      - postgres

#volumes:
#  kiss_demo_pg_data:
#    external: true
#  kiss_demo_mongo_data:
#    external: true
