spring:
  datasource:
    username: ${USERS_USERNAME:demo}
    password: ${USERS_PASSWORD:secret}
    url: ${USERS_DB:jdbc:postgresql://localhost:5432/kiss-demo?currentSchema=users}

server:
  port: 6010

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) <%X{TOKEN}> [%X{USERNAME}] %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
