spring:
  datasource:
    username: ${USERS_USERNAME:demo}
    password: ${USERS_PASSWORD:secret}
    url: ${USERS_DB:jdbc:postgresql://localhost:5432/kiss-demo?currentSchema=users}

server:
  port: 6010
